credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              id: "github-credentials-token"
              description: "Github Credentials Token"
              scope: GLOBAL
              username: "${GITHUB_USERNAME}"
              password: "${GITHUB_TOKEN}"
          - string:
              id: "github-token"
              description: "Github Token"
              scope: GLOBAL
              secret: "${GITHUB_TOKEN}"